### ISSUE TITLE
Beware of the Maintainability Index

### ISSUE THREAD

**Issue by avandeursen** [jared-stilwell/escomplex#20]
Thanks for maintaining a helpful JavaScript metrics project. 

One of the metrics you offer, the "Maintainability Index", however, is an outdated metric that has some serious problems. There are several research papers essentially drawing this conclusion. I have summarized these papers in a blog post [Think Twice Before Using the “Maintainability Index”](https://avandeursen.com/2014/08/29/think-twice-before-using-the-maintainability-index/).

Maybe it would be useful to add a pointer to this blog post in your [Links to Research](https://github.com/jared-stilwell/escomplex#links-to-research) section in your README? If you agree, let me know and I can create a pull request.

(Some of my students are happily using escomplex, but then unfortunately also draw unjustified conclusions based on the "Maintainability Index". A warning might help.)

**Comment by jared-stilwell** [comment]
Agreed. I've found the maintainability index and Halstead metrics to be entirely too mysterious to get much practical use in the day to day. I'm fine with you including a link, but it may be better as an aside in the list of metric descriptions, just so folks know what they're in for.

I can possibly see disabling certain metrics by default in a future version, but I don't have enough evidence from JavaScript projects in the wild to justify it yet.

**Comment by forivall** [comment]
For example, this has a low maintainability index: https://gist.github.com/forivall/666afde0cab7403671955da9e02b4671
